/* This DDL is based on data schema version 1.0 */
CREATE TABLE asu_funcarea_retailareaaggregated (
	featureid uniqueidentifier not null,
	versiondate date not null,
	versionavailablefromdate datetime not null,
	versionavailabletodate datetime,
	changetype nvarchar(50) not null,
	geometry geometry not null,
	geometry_area_m2 numeric(15,3) not null,
	theme nvarchar(40) not null,
	description nvarchar(25) not null,
	name1_text nvarchar(254) not null,
	name1_language nvarchar(3),
	name2_text nvarchar(254),
	name2_language nvarchar(3),
	builtupareaid nvarchar(10),
	builtupareaid_publicationyear integer,
	builtupareaid_count integer not null,
	addresscount_total integer not null,
	addresscount_retail integer not null,
	addresscount_office integer not null,
	addresscount_industrial integer not null,
	addresscount_residential integer not null,
	addresscount_other integer not null,
	retailhierarchy nvarchar(25) not null,
	retailareacount_majorretail integer not null,
	retailareacount_minorretail integer not null,
	retailareacount_standalonebuilding integer not null,
	easting numeric(8,2) not null,
	northing numeric(9,2) not null,
	longitude numeric(9,7) not null,
	latitude numeric(9,7) not null,
	PRIMARY KEY (featureid)
);
CREATE TABLE asu_funcarea_retailareaaggregated_rltenty (
	relatedentityid uniqueidentifier not null,
	featuretypeid nvarchar(36) not null,
	featuretypeversiondate date not null,
	crossreferencefeature nvarchar(50) not null,
	crossreferenceid nvarchar(36) not null,
	relationshiptype nvarchar(30) not null,
	PRIMARY KEY (relatedentityid,featuretypeversiondate)
);
