/* This DDL is based on data schema version 1.0 */
CREATE TABLE ASU_FUNCAREA_RETAILAREAMINOR (
	FEATUREID VARCHAR2(36) not null,
	VERSIONDATE DATE not null,
	VERSIONAVAILABLEFROMDATE TIMESTAMP not null,
	VERSIONAVAILABLETODATE TIMESTAMP,
	CHANGETYPE VARCHAR2(50) not null,
	GEOMETRY SDO_GEOMETRY not null,
	GEOMETRY_AREA_M2 NUMERIC(15,3) not null,
	THEME VARCHAR2(40) not null,
	DESCRIPTION VARCHAR2(25) not null,
	DIVIDINGFEATURE_SITEID VARCHAR2(36),
	DIVIDINGFEATURE_NAME1_TEXT VARCHAR2(254),
	DIVIDINGFEATURE_NAME1_LANGUAGE VARCHAR2(3),
	DIVIDINGFEATURE_NAME2_TEXT VARCHAR2(254),
	DIVIDINGFEATURE_NAME2_LANGUAGE VARCHAR2(3),
	DIVIDINGFEATURE_NAME3_TEXT VARCHAR2(254),
	DIVIDINGFEATURE_NAME3_LANGUAGE VARCHAR2(3),
	DIVIDINGFEATURE_NAME4_TEXT VARCHAR2(254),
	DIVIDINGFEATURE_NAME4_LANGUAGE VARCHAR2(3),
	OSLANDUSETIERA VARCHAR2(50),
	ADDRESSCOUNT_RETAIL NUMBER(3) not null,
	RETAILAREAAGGREGATEDID VARCHAR2(36),
	EASTING NUMERIC(8,2) not null,
	NORTHING NUMERIC(9,2) not null,
	LONGITUDE NUMERIC(9,7) not null,
	LATITUDE NUMERIC(9,7) not null,
	PRIMARY KEY (FEATUREID)
);
CREATE TABLE ASU_FUNCAREA_RETAILAREAMINOR_RLTENTY (
	RELATEDENTITYID VARCHAR2(36) not null,
	FEATURETYPEID VARCHAR2(36) not null,
	FEATURETYPEVERSIONDATE DATE not null,
	CROSSREFERENCEFEATURE VARCHAR2(50) not null,
	CROSSREFERENCEID VARCHAR2(36) not null,
	RELATIONSHIPTYPE VARCHAR2(30) not null,
	PRIMARY KEY (RELATEDENTITYID,FEATURETYPEVERSIONDATE)
);
